-- Sample Seed Data for Menu Tree System
-- Note: UUIDs are examples. Use the actual IDs generated by your system.

-- Main Menu
INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
VALUES (gen_random_uuid(), 'System Settings', NULL, 1, NOW(), NOW());

-- Sub-menus for System Settings
-- Assuming the ID above is '550e8400-e29b-41d4-a716-446655440000'
INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
SELECT gen_random_uuid(), 'User Management', id, 1, NOW(), NOW() FROM menus WHERE name = 'System Settings';

INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
SELECT gen_random_uuid(), 'Role Permissions', id, 2, NOW(), NOW() FROM menus WHERE name = 'System Settings';

-- Reports Menu
INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
VALUES (gen_random_uuid(), 'Reports', NULL, 2, NOW(), NOW());

-- Sub-menus for Reports
INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
SELECT gen_random_uuid(), 'Financial Reports', id, 1, NOW(), NOW() FROM menus WHERE name = 'Reports';

INSERT INTO menus (id, name, parent_id, "order", created_at, updated_at) 
SELECT gen_random_uuid(), 'Audit Logs', id, 2, NOW(), NOW() FROM menus WHERE name = 'Reports';
